version: 2021.05

base:
  registry: dockerhub # supported values are `gcr`, `ecr` and `dockerhub`
  image: alpine
  container: alpine

  env:
    CLOUD: aws # supported clouds: aws, gcp
    REGION: us-east-1

  mounts:
    $HOME/.ssh: /root/.ssh
    $HOME/.gitconfig: /root/.gitconfig
    $HOME/.aws: /root/.aws
    $HOME/.config/gh: /root/.config/gh
    $HOME/.cfconfig: /root/.cfconfig

contexts:
  cluster1:
    env:
      KUBE_CONTEXT: cluster1
      # REGION: us-east-2
  cluster2:
    env:
      KUBE_CONTEXT: cluster2
